version: '3.8'
services:
  web:
    build: ./app
    restart: always
    volumes:
      - ./app:/usr/src/app
    expose:
      - 5000
    depends_on:
      - redis_db
  nginx:
    build: ./app/nginx
    restart: always
    volumes:
      - ./app:/usr/src/app/nginx
    ports:
      - 80:8080
    depends_on:
      - web

  redis_db:
    image: redislabs/redisearch:edge
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ${PWD}:/usr/src/app/redis
